[env]
TERM = "xterm-256color"

[window]
padding.x = 6 
padding.y = 6 
decorations = "Buttonless"
opacity = 0.8
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"


[scrolling]
multiplier = 3

[mouse]
hide_when_typing = true

[font]
 normal.family = "JetBrainsMono Nerd Font Mono"
# normal.family = "FiraMono Nerd Font Mono"

size = 12.25 
# offset.x = 1  
offset.y = 4 
glyph_offset.y = 2 

[colors.normal] 
blue = "#2e89ff" 
yellow = "#d29922"
